services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - ${PG_PORT}:${PG_PORT}
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - drupal-db:/var/lib/postgresql/data
    networks:
      - drupal-network

volumes:
  drupal-db:
    name: drupal-db

networks:
  drupal-network:
    name: drupal-network