services:
  node:
    image: rorem/helloworld
    container_name: hello-world
    ports:
      - ${PORT}:${PORT}
    expose:
      - ${PORT}
    environment:
      - NAME
      - PORT
      - SERVER_URL
    volumes:
      - ./dist/index.js:/server/index.js